services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8080"
    restart: unless-stopped
    environment:
      PORT: "8080"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      MONGODB_URI: ${MONGODB_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  url-shortener-service:
    build:
      context: ./url-shortener-service
      dockerfile: Dockerfile
    container_name: url-shortener-service
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis-init
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      AUTH_SERVICE_URL: http://auth-service:8080
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:8
    command: redis-server --appendonly yes

  redis-init:
    build: ./redis-init
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379

  postgres:
    image: postgres:17
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./auth-service/docs/openapi.yaml:/app/openapi.yaml
    environment:
      SWAGGER_JSON: /app/openapi.yaml
      BASE_URL: /docs
    restart: unless-stopped

volumes:
  pgdata:
